Remove typedef from yacc.c
This causes "redefinition of typedef 'YYSTYPE' is a C11 feature"
for C99 compiler on ruby/ruby CI.

```
In file included from parse.y:287:
parse.h:215:23: error: redefinition of typedef 'YYSTYPE' is a C11 feature [-Werror,-Wtypedef-redefinition]
  215 | typedef union YYSTYPE YYSTYPE;
      |                       ^
../src/parse.c:67:23: note: previous definition is here
   67 | typedef union YYSTYPE YYSTYPE;
      |                       ^
1 error generated.
make: *** [Makefile:447: parse.o] Error 1
```

See: https://github.com/yui-knk/ruby/actions/runs/6752689795/job/18358348840