Fix errors that conflict with C++ reserved words
```
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1196:3: error: expected identifier
  delete,
  ^
 ```