Fix errors that conflict with C++ reserved words
```
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1437:31: error: expected unqualified-id
                  yy_repairs *new = (yy_repairs *) YYMALLOC (sizeof (yy_repairs));
                              ^
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1438:22: error: expected a type
                  new->id = count;
                     ^
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1439:22: error: expected a type
                  new->next = 0;
                     ^
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1440:22: error: expected a type
                  new->stack_length = stack_length;
                     ^
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1441:22: error: expected a type
                  new->states = (yy_state_t *) YYMALLOC (sizeof (yy_state_t) * (stack_length));
                     ^
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1442:22: error: expected a type
                  new->state = new->states + (current->state - current->states);
                     ^
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1443:30: error: expected a type
                  YYCOPY (new->states, current->states, current->state - current->states + 1);
                             ^
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1444:22: error: expected a type
                  new->repair_length = current->repair_length + 1;
                     ^
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1445:22: error: expected a type
                  new->prev_repair = current;
                     ^
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1446:22: error: expected a type
                  new->repair.type = insert;
                     ^
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1447:22: error: expected a type
                  new->repair.term = (yysymbol_kind_t) yyx;
                     ^
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1450:48: error: expected a type
                  if (! yy_process_repairs (new, yyx))
                                               ^
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1452:34: error: expected a type
                      YYFREE (new);
                                 ^
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1457:29: error: expected a type
                  tail = new;
                            ^
/var/folders/7d/3dfz8sj91zjdmmzwzz1pw84r0000gp/T/error_recovery.cpp:1473:40: error: expected a type
                  yy_print_repairs (new);
                                       ^
 ```